### ISSUE TITLE
As a tester, I want to see documentation of the framework, so that I can understand how to use it

### ISSUE THREAD

**Issue by kxrtiswithak** [tenioe/open-weather-api#4]
### Acceptance Criteria

**GIVEN** a tester wants to use the framework
**WHEN** they view the code or the readme.md
**THEN** they are greeted with javadoc comments for each method in the code
**AND** usage instructions within the readme.md

---

### Test Cases

- [ ] each method has its javadoc comment
- [ ] the readme contains a section explaining how to use the framework
- [ ] usage includes explanation about api key within a properties file
